//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendTestSms.NicKiiSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NicKiiSms.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name appid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSsend", ReplyAction="*")]
        SendTestSms.NicKiiSms.SMSsendResponse SMSsend(SendTestSms.NicKiiSms.SMSsendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSsend", ReplyAction="*")]
        System.Threading.Tasks.Task<SendTestSms.NicKiiSms.SMSsendResponse> SMSsendAsync(SendTestSms.NicKiiSms.SMSsendRequest request);
        
        // CODEGEN: Generating message contract since element name appid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSsend_V2", ReplyAction="*")]
        SendTestSms.NicKiiSms.SMSsend_V2Response SMSsend_V2(SendTestSms.NicKiiSms.SMSsend_V2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSsend_V2", ReplyAction="*")]
        System.Threading.Tasks.Task<SendTestSms.NicKiiSms.SMSsend_V2Response> SMSsend_V2Async(SendTestSms.NicKiiSms.SMSsend_V2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSsendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSsend", Namespace="http://tempuri.org/", Order=0)]
        public SendTestSms.NicKiiSms.SMSsendRequestBody Body;
        
        public SMSsendRequest() {
        }
        
        public SMSsendRequest(SendTestSms.NicKiiSms.SMSsendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSsendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int SRNO;
        
        public SMSsendRequestBody() {
        }
        
        public SMSsendRequestBody(string appid, string pwd, string smsto, string msg, int SRNO) {
            this.appid = appid;
            this.pwd = pwd;
            this.smsto = smsto;
            this.msg = msg;
            this.SRNO = SRNO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSsendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSsendResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendTestSms.NicKiiSms.SMSsendResponseBody Body;
        
        public SMSsendResponse() {
        }
        
        public SMSsendResponse(SendTestSms.NicKiiSms.SMSsendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSsendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SMSsendResult;
        
        public SMSsendResponseBody() {
        }
        
        public SMSsendResponseBody(bool SMSsendResult) {
            this.SMSsendResult = SMSsendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSsend_V2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSsend_V2", Namespace="http://tempuri.org/", Order=0)]
        public SendTestSms.NicKiiSms.SMSsend_V2RequestBody Body;
        
        public SMSsend_V2Request() {
        }
        
        public SMSsend_V2Request(SendTestSms.NicKiiSms.SMSsend_V2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSsend_V2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string template_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int SRNO;
        
        public SMSsend_V2RequestBody() {
        }
        
        public SMSsend_V2RequestBody(string appid, string pwd, string smsto, string msg, string template_id, int SRNO) {
            this.appid = appid;
            this.pwd = pwd;
            this.smsto = smsto;
            this.msg = msg;
            this.template_id = template_id;
            this.SRNO = SRNO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSsend_V2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSsend_V2Response", Namespace="http://tempuri.org/", Order=0)]
        public SendTestSms.NicKiiSms.SMSsend_V2ResponseBody Body;
        
        public SMSsend_V2Response() {
        }
        
        public SMSsend_V2Response(SendTestSms.NicKiiSms.SMSsend_V2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSsend_V2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SMSsend_V2Result;
        
        public SMSsend_V2ResponseBody() {
        }
        
        public SMSsend_V2ResponseBody(bool SMSsend_V2Result) {
            this.SMSsend_V2Result = SMSsend_V2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : SendTestSms.NicKiiSms.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<SendTestSms.NicKiiSms.Service1Soap>, SendTestSms.NicKiiSms.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendTestSms.NicKiiSms.SMSsendResponse SendTestSms.NicKiiSms.Service1Soap.SMSsend(SendTestSms.NicKiiSms.SMSsendRequest request) {
            return base.Channel.SMSsend(request);
        }
        
        public bool SMSsend(string appid, string pwd, string smsto, string msg, int SRNO) {
            SendTestSms.NicKiiSms.SMSsendRequest inValue = new SendTestSms.NicKiiSms.SMSsendRequest();
            inValue.Body = new SendTestSms.NicKiiSms.SMSsendRequestBody();
            inValue.Body.appid = appid;
            inValue.Body.pwd = pwd;
            inValue.Body.smsto = smsto;
            inValue.Body.msg = msg;
            inValue.Body.SRNO = SRNO;
            SendTestSms.NicKiiSms.SMSsendResponse retVal = ((SendTestSms.NicKiiSms.Service1Soap)(this)).SMSsend(inValue);
            return retVal.Body.SMSsendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendTestSms.NicKiiSms.SMSsendResponse> SendTestSms.NicKiiSms.Service1Soap.SMSsendAsync(SendTestSms.NicKiiSms.SMSsendRequest request) {
            return base.Channel.SMSsendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendTestSms.NicKiiSms.SMSsendResponse> SMSsendAsync(string appid, string pwd, string smsto, string msg, int SRNO) {
            SendTestSms.NicKiiSms.SMSsendRequest inValue = new SendTestSms.NicKiiSms.SMSsendRequest();
            inValue.Body = new SendTestSms.NicKiiSms.SMSsendRequestBody();
            inValue.Body.appid = appid;
            inValue.Body.pwd = pwd;
            inValue.Body.smsto = smsto;
            inValue.Body.msg = msg;
            inValue.Body.SRNO = SRNO;
            return ((SendTestSms.NicKiiSms.Service1Soap)(this)).SMSsendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendTestSms.NicKiiSms.SMSsend_V2Response SendTestSms.NicKiiSms.Service1Soap.SMSsend_V2(SendTestSms.NicKiiSms.SMSsend_V2Request request) {
            return base.Channel.SMSsend_V2(request);
        }
        
        public bool SMSsend_V2(string appid, string pwd, string smsto, string msg, string template_id, int SRNO) {
            SendTestSms.NicKiiSms.SMSsend_V2Request inValue = new SendTestSms.NicKiiSms.SMSsend_V2Request();
            inValue.Body = new SendTestSms.NicKiiSms.SMSsend_V2RequestBody();
            inValue.Body.appid = appid;
            inValue.Body.pwd = pwd;
            inValue.Body.smsto = smsto;
            inValue.Body.msg = msg;
            inValue.Body.template_id = template_id;
            inValue.Body.SRNO = SRNO;
            SendTestSms.NicKiiSms.SMSsend_V2Response retVal = ((SendTestSms.NicKiiSms.Service1Soap)(this)).SMSsend_V2(inValue);
            return retVal.Body.SMSsend_V2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendTestSms.NicKiiSms.SMSsend_V2Response> SendTestSms.NicKiiSms.Service1Soap.SMSsend_V2Async(SendTestSms.NicKiiSms.SMSsend_V2Request request) {
            return base.Channel.SMSsend_V2Async(request);
        }
        
        public System.Threading.Tasks.Task<SendTestSms.NicKiiSms.SMSsend_V2Response> SMSsend_V2Async(string appid, string pwd, string smsto, string msg, string template_id, int SRNO) {
            SendTestSms.NicKiiSms.SMSsend_V2Request inValue = new SendTestSms.NicKiiSms.SMSsend_V2Request();
            inValue.Body = new SendTestSms.NicKiiSms.SMSsend_V2RequestBody();
            inValue.Body.appid = appid;
            inValue.Body.pwd = pwd;
            inValue.Body.smsto = smsto;
            inValue.Body.msg = msg;
            inValue.Body.template_id = template_id;
            inValue.Body.SRNO = SRNO;
            return ((SendTestSms.NicKiiSms.Service1Soap)(this)).SMSsend_V2Async(inValue);
        }
    }
}
